To be converted to scripts eventually?

Desired columns for LIB

- publisher ?
- title (from "title") 
- subject 1, subject 2, subject 3, (or more?), 
- se subjects
- series from "belongs-to-collection"?
- detective (add later) 
- collection type from "collection type"
- series position from "group-position"
- short description from "description"
- long description from "long-description"
- language from dc:language
- se word-count from "se:word-count"
- flesch scale from "se:reading-ease.flesch"
- source_url from "se:url.vcs.github"
- author from "author"
- author full name? from "se:name.person.full-name" (DON'T NEED)
- wikipedia url from "se:url.encyclopedia.wikipedia"
- number of chapters (DO LATER IN CORPUS)
- written_as (manually)
- work_type (manually)
- alt_titles (LATER) (manually)

Design decisions:
- choosing to treat each story in poirot investigates as its own document since the stories are the unit of composition (4/9/26)

## Raw Data Ingestion

The script below was run once to clone the corpus repositories from Standard Ebooks. 
It is preserved here for reproducibility. Do not re-run — raw_data/ is already populated.

```bash
#!/bin/bash
# Ingestion script for Agatha Christie Standard Ebooks Corpus

mkdir raw_data
cd raw_data

echo "Cloning repositories..."
git clone --depth 1 git@github.com:standardebooks/agatha-christie_the-murder-at-the-vicarage.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_giants-bread.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_the-secret-adversary.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_the-murder-on-the-links.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_the-man-in-the-brown-suit.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_the-big-four.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_poirot-investigates.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_the-mysterious-affair-at-styles.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_the-secret-of-chimneys.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_the-seven-dials-mystery.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_the-murder-of-roger-ackroyd.git
git clone --depth 1 git@github.com:standardebooks/agatha-christie_the-mystery-of-the-blue-train.git

echo "Ingestion complete."
```

## Construct LIB table

In [39]:
# import libraries
import pandas as pd
import glob
import os
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from bs4 import BeautifulSoup

In [40]:
# # get list of all files in the raw_data folder
# root_dir = 'raw_data'
# file_list = []

# for root, dirs, files in os.walk(root_dir):
#     for file in files:
#         # Join the folder path and file name to get the full path
#         full_path = os.path.join(root, file)
#         file_list.append(full_path)

# file_list

In [41]:
# helper functions for if a field is missing in the content.opf file, return None instead of throwing an error
def get_metadata(root, property_val, NS):
    el = root.find(f'opf:metadata/opf:meta[@property="{property_val}"]', NS)
    return el.text if el is not None else None

def get_dc(root, tag, NS):
    el = root.find(f'opf:metadata/dc:{tag}', NS)
    return el.text if el is not None else None

In [42]:
# specify root directory (or hardcode?)
root_dir = 'raw_data'

# define namespaces used in StandardEbooks opf files (namespaces avoid tag collisions when multiple vocabularies are in one document)
NS = {
    'opf':  'http://www.idpf.org/2007/opf', # open packaging format
    'dc':   'http://purl.org/dc/elements/1.1/', # dublin core vocabulary (dublin core metadata terms)
    'rdf':  'http://www.w3.org/1999/02/22-rdf-syntax-ns#', # resource description framework
}

# get content.opf file paths
opf_files = sorted(Path(root_dir).glob('*/src/epub/content.opf'))

# initialize empty list to store book info and path
book_data = [] # a list of dictionaries, where each dictionary contains the book info for one book

for opf_path in opf_files:
    # get the book_id from the folder name
    book_id = opf_path.parts[1].replace('agatha-christie_', '') # .parts breaks a path into a tuple of components
    
    # initalize a list for subjects and se_subjects
    subjects = []
    se_subjects = []
    # get the tree and root for ElementTree parsing
    tree = ET.parse(opf_path)
    root = tree.getroot()

    # parse opf file and extract relevant fields
    publisher = get_dc(root, 'publisher', NS) # use helper function to guard against missing field
    title = get_dc(root, 'title', NS)
    series = get_metadata(root, 'belongs-to-collection', NS)
    col_type = get_metadata(root, 'collection-type', NS)
    series_pos = get_metadata(root, 'group-position', NS)
    short_desc = get_dc(root, 'description', NS)
    long_desc = get_metadata(root, 'se:long-description', NS)
    language = get_dc(root, 'language', NS)
    se_word_count = get_metadata(root, 'se:word-count', NS)
    se_reading_ease = get_metadata(root, 'se:reading-ease.flesch', NS)
    source_url = get_metadata(root, 'se:url.vcs.github', NS)
    author = get_dc(root, 'creator', NS)
    wikipedia_url = get_metadata(root, 'se:url.encyclopedia.wikipedia', NS)

    # for each subject in the content.opf file, append to subjects list
    subject_els = root.findall('opf:metadata/dc:subject', NS)
    subjects = '|'.join([el.text for el in subject_els]) if subject_els else None # join and separate subjects with pipe and guard against missing field

    se_subject_els = root.findall('opf:metadata/opf:meta[@property="se:subject"]', NS)
    se_subjects = '|'.join([el.text for el in se_subject_els]) if se_subject_els else None

    # append extracted fields to book_data list as a dictionary
    book_data.append({
        'book_id': book_id,
        'publisher': publisher,
        'title': title,
        'author': author,
        'subjects': subjects,
        'se_subjects': se_subjects,
        'col_type': col_type,
        'series': series,
        'series_pos': series_pos,
        'short_desc': short_desc,
        'long_desc': long_desc,
        'language': language,
        'se_word_count': se_word_count,
        'se_reading_ease': se_reading_ease,
        'source_url': source_url,
        'wikipedia_url': wikipedia_url,
    })

# build dataframe from book_data list and set book_id as index
LIB = pd.DataFrame(book_data).set_index('book_id')
LIB

,publisher,title,author,subjects,se_subjects,col_type,series,series_pos,short_desc,long_desc,language,se_word_count,se_reading_ease,source_url,wikipedia_url
book_id,,,,,,,,,,,,,,,
giants-bread,Standard Ebooks,Giant’s Bread,Agatha Christie,"Psychological fiction, English|Composers--Fiction",Fiction,NaN,NaN,NaN,The genesis of a monumental piece of music is ...,\n\t\t\t<p>Vernon Deyre lives with his parents...,en-GB,101165,78.45,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/Giant%27s_Bread
poirot-investigates,Standard Ebooks,Poirot Investigates,Agatha Christie,Private investigators -- England -- Fiction|De...,Mystery|Shorts,series,Poirot,3,A calculating Belgian detective and his wide-e...,\n\t\t\t<p><i>Poirot Investigates</i> is a cla...,en-GB,52707,76.72,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/Poirot_Investigates
the-big-four,Standard Ebooks,The Big Four,Agatha Christie,Private investigators -- England -- Fiction|De...,Mystery,series,Poirot,5,A famous detective must use all his little gre...,\n\t\t\t<p>“The American Soap King” has offere...,en-GB,55818,76.62,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Big_Four_(no...
the-man-in-the-brown-suit,Standard Ebooks,The Man in the Brown Suit,Agatha Christie,South Africa -- Fiction|Detective and mystery ...,Adventure|Fiction|Mystery,series,Colonel Race,1,Anne Beddingfeld travels to South Africa after...,"\n\t\t\t<p>After her father’s death, young Ann...",en-GB,75682,76.82,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Man_in_the_B...
the-murder-at-the-vicarage,Standard Ebooks,The Murder at the Vicarage,Agatha Christie,"Marple, Jane (Fictitious character)--Fiction|W...",Fiction|Mystery,series,Miss Marple,1,A vicar attempts to unravel the mystery of a m...,\n\t\t\t<p>Not much happens in the sleepy rura...,en-GB,70129,77.84,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Murder_at_th...
the-murder-of-roger-ackroyd,Standard Ebooks,The Murder of Roger Ackroyd,Agatha Christie,Private investigators -- England -- Fiction|De...,Mystery,series,Poirot,4,A legendary Belgian detective comes out of ret...,\n\t\t\t<p>Hercule Poirot has retired to the E...,en-GB,70105,77.84,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Murder_of_Ro...
the-murder-on-the-links,Standard Ebooks,The Murder on the Links,Agatha Christie,"Poirot, Hercule (Fictitious character)--Fictio...",Fiction|Mystery,series,Poirot,2,A famous Belgian detective and his sidekick ar...,\n\t\t\t<p><i>The Murder on the Links</i> is <...,en-GB,64890,77.33,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Murder_on_th...
the-mysterious-affair-at-styles,Standard Ebooks,The Mysterious Affair at Styles,Agatha Christie,"Poirot, Hercule (Fictitious character)--Fictio...",Fiction|Mystery,series,Poirot,1,A fastidious Belgian detective solves the myst...,\n\t\t\t<p><i>The Mysterious Affair at Styles<...,en-GB,56894,77.03,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Mysterious_A...
the-mystery-of-the-blue-train,Standard Ebooks,The Mystery of the Blue Train,Agatha Christie,Private investigators--England--Fiction|Railro...,Fiction|Mystery,series,Poirot,6,A retired detective finds himself at the scene...,\n\t\t\t<p><i>The Mystery of the Blue Train</i...,en-GB,70358,77.23,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Mystery_of_t...
the-secret-adversary,Standard Ebooks,The Secret Adversary,Agatha Christie,Private investigators -- England -- Fiction|De...,Fiction|Mystery,series,Tommy and Tuppence,1,"Tommy and Tuppence try to solve a mystery, onl...","\n\t\t\t<p><i>The Secret Adversary</i>, <a hre...",en-GB,75651,78.14,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Secret_Adver...
the-secret-of-chimneys,Standard Ebooks,The Secret of Chimneys,Agatha Christie,Detective and mystery stories|Police -- Englan...,Fiction|Mystery,series,Superintendent Battle,1,A murder at a country house embroils its weeke...,"\n\t\t\t<p>Anthony Cade, a quick-witted rogue ...",en-GB,74867,77.84,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Secret_of_Ch...
the-seven-dials-mystery,Standard Ebooks,The Seven Dials Mystery,Agatha Christie,Superintendent Battle (Fictitious character) -...,Fiction|Mystery,series,Superintendent Battle,2,A weekend party at a country mansion ends in m...,"\n\t\t\t<p>The country mansion Chimneys, the s...",en-GB,65723,78.25,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Seven_Dials_...

In [43]:
# add manual fields
# add work type, writing_as, pub_year_original, genre, and sleuth by hand (from agathachristie.com and the agatha christie reading list app):
work_type = { # from the website
    'giants-bread': 'novel', # confirmed
    'poirot-investigates': 'collection of short stories', # confirmed
    'the-big-four': 'novel', # confirmed
    'the-man-in-the-brown-suit': 'novel', # confirmed
    'the-murder-at-the-vicarage': 'novel', # confirmed
    'the-murder-of-roger-ackroyd': 'novel', # confirmed
    'the-murder-on-the-links': 'novel', # confirmed
    'the-mysterious-affair-at-styles': 'novel', # confirmed
    'the-mystery-of-the-blue-train': 'novel', # confirmed
    'the-secret-adversary': 'novel', # confirmed
    'the-secret-of-chimneys': 'novel', # confirmed
    'the-seven-dials-mystery': 'novel' # confirmed
}

writing_as = { # from the website
    'giants-bread': 'Mary Westmacott', # confirmed
    'poirot-investigates': 'Agatha Christie', # confirmed
    'the-big-four': 'Agatha Christie', # confirmed
    'the-man-in-the-brown-suit': 'Agatha Christie', # confirmed
    'the-murder-at-the-vicarage': 'Agatha Christie', # confirmed
    'the-murder-of-roger-ackroyd': 'Agatha Christie', # confirmed
    'the-murder-on-the-links': 'Agatha Christie', # confirmed
    'the-mysterious-affair-at-styles': 'Agatha Christie', # confirmed
    'the-mystery-of-the-blue-train': 'Agatha Christie', # confirmed
    'the-secret-adversary': 'Agatha Christie', # confirmed
    'the-secret-of-chimneys': 'Agatha Christie', # confirmed
    'the-seven-dials-mystery': 'Agatha Christie' # confirmed
}

pub_year_original = { # from the website
    'giants-bread': 1930, # confirmed
    'poirot-investigates': 1924, # confirmed
    'the-big-four': 1927, # confirmed
    'the-man-in-the-brown-suit': 1924, # confirmed
    'the-murder-at-the-vicarage': 1930, # confirmed
    'the-murder-of-roger-ackroyd': 1926, # confirmed
    'the-murder-on-the-links': 1923, # confirmed
    'the-mysterious-affair-at-styles': 1920, # confirmed
    'the-mystery-of-the-blue-train': 1928, # confirmed
    'the-secret-adversary': 1922, # confirmed
    'the-secret-of-chimneys': 1925, # confirmed
    'the-seven-dials-mystery': 1929, # confirmed
}

genre = { # from the app
    'giants-bread': "Romance", # confirmed
    'poirot-investigates': "Murder Mystery|Detective|Thriller|Espionage", # confirmed
    'the-big-four': "Detective|Espionage|Thriller", # confirmed
    'the-man-in-the-brown-suit': "Murder Mystery|Thriller", # confirmed
    'the-murder-at-the-vicarage': "Murder Mystery", # confirmed
    'the-murder-of-roger-ackroyd': "Murder Mystery|Detective", # confirmed
    'the-murder-on-the-links': "Murder Mystery|Detective", # confirmed
    'the-mysterious-affair-at-styles': "Murder Mystery|Detective", # confirmed
    'the-mystery-of-the-blue-train': "Murder Mystery|Detective", # confirmed
    'the-secret-adversary': "Espionage|Thriller", # confirmed
    'the-secret-of-chimneys': "Espionage", # confirmed
    'the-seven-dials-mystery': "Espionage|Thriller", # confirmed
}

sleuth = { # from the app
    'giants-bread': None, # confirmed
    'poirot-investigates': "Hercule Poirot", # confirmed
    'the-big-four': "Hercule Poirot", # confirmed
    'the-man-in-the-brown-suit': "Colonel Race", # confirmed
    'the-murder-at-the-vicarage': "Miss Jane Marple", # confirmed
    'the-murder-of-roger-ackroyd': "Hercule Poirot", # confirmed
    'the-murder-on-the-links': "Hercule Poirot", # confirmed
    'the-mysterious-affair-at-styles': "Hercule Poirot", # confirmed
    'the-mystery-of-the-blue-train': "Hercule Poirot", # confirmed
    'the-secret-adversary': "Tommy and Tuppence", # confirmed
    'the-secret-of-chimneys': "Superintendent Battle", # confirmed
    'the-seven-dials-mystery': "Superintendent Battle", # confirmed
}

# join the dictionaries to LIB
LIB['pub_year_original'] = LIB.index.map(pub_year_original)
LIB['writing_as'] = LIB.index.map(writing_as)
LIB['work_type'] = LIB.index.map(work_type)
LIB['genre'] = LIB.index.map(genre)
LIB['sleuth'] = LIB.index.map(sleuth)

LIB

,publisher,title,author,subjects,se_subjects,col_type,series,series_pos,short_desc,long_desc,language,se_word_count,se_reading_ease,source_url,wikipedia_url,pub_year_original,writing_as,work_type,genre,sleuth
book_id,,,,,,,,,,,,,,,,,,,,
giants-bread,Standard Ebooks,Giant’s Bread,Agatha Christie,"Psychological fiction, English|Composers--Fiction",Fiction,NaN,NaN,NaN,The genesis of a monumental piece of music is ...,\n\t\t\t<p>Vernon Deyre lives with his parents...,en-GB,101165,78.45,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/Giant%27s_Bread,1930,Mary Westmacott,novel,Romance,NaN
poirot-investigates,Standard Ebooks,Poirot Investigates,Agatha Christie,Private investigators -- England -- Fiction|De...,Mystery|Shorts,series,Poirot,3,A calculating Belgian detective and his wide-e...,\n\t\t\t<p><i>Poirot Investigates</i> is a cla...,en-GB,52707,76.72,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/Poirot_Investigates,1924,Agatha Christie,collection of short stories,Murder Mystery|Detective|Thriller|Espionage,Hercule Poirot
the-big-four,Standard Ebooks,The Big Four,Agatha Christie,Private investigators -- England -- Fiction|De...,Mystery,series,Poirot,5,A famous detective must use all his little gre...,\n\t\t\t<p>“The American Soap King” has offere...,en-GB,55818,76.62,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Big_Four_(no...,1927,Agatha Christie,novel,Detective|Espionage|Thriller,Hercule Poirot
the-man-in-the-brown-suit,Standard Ebooks,The Man in the Brown Suit,Agatha Christie,South Africa -- Fiction|Detective and mystery ...,Adventure|Fiction|Mystery,series,Colonel Race,1,Anne Beddingfeld travels to South Africa after...,"\n\t\t\t<p>After her father’s death, young Ann...",en-GB,75682,76.82,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Man_in_the_B...,1924,Agatha Christie,novel,Murder Mystery|Thriller,Colonel Race
the-murder-at-the-vicarage,Standard Ebooks,The Murder at the Vicarage,Agatha Christie,"Marple, Jane (Fictitious character)--Fiction|W...",Fiction|Mystery,series,Miss Marple,1,A vicar attempts to unravel the mystery of a m...,\n\t\t\t<p>Not much happens in the sleepy rura...,en-GB,70129,77.84,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Murder_at_th...,1930,Agatha Christie,novel,Murder Mystery,Miss Jane Marple
the-murder-of-roger-ackroyd,Standard Ebooks,The Murder of Roger Ackroyd,Agatha Christie,Private investigators -- England -- Fiction|De...,Mystery,series,Poirot,4,A legendary Belgian detective comes out of ret...,\n\t\t\t<p>Hercule Poirot has retired to the E...,en-GB,70105,77.84,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Murder_of_Ro...,1926,Agatha Christie,novel,Murder Mystery|Detective,Hercule Poirot
the-murder-on-the-links,Standard Ebooks,The Murder on the Links,Agatha Christie,"Poirot, Hercule (Fictitious character)--Fictio...",Fiction|Mystery,series,Poirot,2,A famous Belgian detective and his sidekick ar...,\n\t\t\t<p><i>The Murder on the Links</i> is <...,en-GB,64890,77.33,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Murder_on_th...,1923,Agatha Christie,novel,Murder Mystery|Detective,Hercule Poirot
the-mysterious-affair-at-styles,Standard Ebooks,The Mysterious Affair at Styles,Agatha Christie,"Poirot, Hercule (Fictitious character)--Fictio...",Fiction|Mystery,series,Poirot,1,A fastidious Belgian detective solves the myst...,\n\t\t\t<p><i>The Mysterious Affair at Styles<...,en-GB,56894,77.03,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Mysterious_A...,1920,Agatha Christie,novel,Murder Mystery|Detective,Hercule Poirot
the-mystery-of-the-blue-train,Standard Ebooks,The Mystery of the Blue Train,Agatha Christie,Private investigators--England--Fiction|Railro...,Fiction|Mystery,series,Poirot,6,A retired detective finds himself at the scene...,\n\t\t\t<p><i>The Mystery of the Blue Train</i...,en-GB,70358,77.23,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Mystery_of_t...,1928,Agatha Christie,novel,Murder Mystery|Detective,Hercule Poirot
the-secret-adversary,Standard Ebooks,The Secret Adversary,Agatha Christie,Private investigators -- England -- Fiction|De...,Fiction|Mystery,series,Tommy and Tuppence,1,"Tommy and Tuppence try to solve a mystery, onl...","\n\t\t\t<p><i>The Secret Adversary</i>, <a hre...",en-GB,75651,78.14,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Secret_Adver...,1922,Agatha Christie,novel,Espionage|Thriller,Tommy and Tuppence
the-secret-of-chimneys,Standard Ebooks,The Secret of Chimneys,Agatha Christie,Detective and mystery stories|Police -- Englan...,Fiction|Mystery,series,Superintendent Battle,1,A murder at a country house embroils its weeke...,"\n\t\t\t<p>Anthony Cade, a quick-witted rogue ...",en-GB,74867,77.84,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Secret_of_Ch...,1925,Agatha Christie,novel,Espionage,Superintendent Battle
the-seven-dials-mystery,Standard Ebooks,The Seven Dials Mystery,Agatha Christie,Superintendent Battle (Fictitious character) -...,Fiction|Mystery,series,Superintendent Battle,2,A weekend party at a country mansion ends in m...,"\n\t\t\t<p>The country mansion Chimneys, the s...",en-GB,65723,78.25,https://github.com/standardebooks/agatha-chris...,https://en.wikipedia.org/wiki/The_Seven_Dials_...,1929,Agatha Christie,novel,Espionage|Thriller,Superintendent Battle

In [44]:
# check for missingness
print(LIB.to_string())
print("\nMissing values:")
print(LIB.isnull().sum())

                                       publisher                            title           author                                                                                                                                                                                                                                                  subjects                se_subjects col_type                 series series_pos                                                                                                                                           short_desc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              long_desc language se_word_count se_reading_ease                                                                         source_url                                                  wikipedia_url  pub_year_original       writing_as                    work_type                                        genre                 sleuth
book_id
giants-bread                     Standard Ebooks                    Giant’s Bread  Agatha Christie                                                                                                                                                                                                         Psychological fiction, English|Composers--Fiction                    Fiction      NaN                    NaN        NaN                                                                 The genesis of a monumental piece of music is described in the life of its composer.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \n\t\t\t<p>Vernon Deyre lives with his parents, Nurse, and a selection of imaginary friends including the enigmatic Mr. Green, at the Deyre’s ancestral home of Abbots Puissants. As he grows, his nebulous fears crystallize into more specific forms, most notably in the Beast: a terrifying piano that symbolizes the way music makes him feel.</p>\n\t\t\t<p>His early inability to engage with music stems from the lack of his hearing the <em>right</em> kind of music, as a later experience at a concert makes very clear. This Titanic Concert triggers an epiphany and sets Vernon on a new life path that will sweep his friends along with him, regardless of their own needs.</p>\n\t\t\t<p><a href="https://standardebooks.org/ebooks/agatha-christie">Agatha Christie</a>, already famous for her <a href="https://standardebooks.org/collections/poirot">Poirot</a> crime stories among others, had determined that a pen name would give her the freedom to pursue other types of literature. <i>Giant’s Bread</i>, originally published in 1930 under the name of Mary Westmacott, was the first of six of these non-crime novels. The press, while stymied over which author had adopted the pen name, were enthusiastic, praising in particular the characterizations.</p>\n\t\t    en-GB        101165           78.45                     https://github.com/standardebooks/agatha-christie_giants-bread                  https://en.wikipedia.org/wiki/Giant%27s_Bread               1930  Mary Westmacott                        novel                                      Romance                    NaN
poirot-investigates              Standard Ebooks              Poirot Investigates  Agatha Christie                                                                                       Private investigators -- England -- Fiction|Detective and mystery stories, English|Belgians -- England -- Fiction|Poirot, Hercule (Fictitious character) -- Fiction             Mystery|Shorts   series                 Poirot          3                                             A calculating Belgian detective and his wide-eyed companion investigate and solve a series of mysteries.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \n\t\t\t<p><i>Poirot Investigates</i> is a classic collection of <a href="https://standardebooks.org/ebooks/agatha-christie">Agatha Christie’s</a> short stories first published in 1924. It follows the famous Belgian detective Hercule Poirot and his companion Arthur Hastings as they solve a series of mysteries. From threatening letters to Egyptian curses to missing wills, Poirot’s little grey cells never falter. While Hastings and the reader are lost in the minutiae of the case, Poirot sees it all—and with impeccable attention to detail, finds the culprit.</p>\n\t\t    en-GB         52707           76.72              https://github.com/standardebooks/agatha-christie_poirot-investigates              https://en.wikipedia.org/wiki/Poirot_Investigates               1924  Agatha Christie  collection of short stories  Murder Mystery|Detective|Thriller|Espionage         Hercule Poirot
the-big-four                     Standard Ebooks                     The Big Four  Agatha Christie                                                                                       Private investigators -- England -- Fiction|Detective and mystery stories, English|Belgians -- England -- Fiction|Poirot, Hercule (Fictitious character) -- Fiction                    Mystery   series                 Poirot          5            A famous detective must use all his little grey cells to stop an immensely powerful and ruthless organization from taking over the world.                                                                                             \n\t\t\t<p>“The American Soap King” has offered <a href="https://standardebooks.org/collections/poirot">Hercule Poirot</a> a ridiculous amount of money to investigate some dodgy business in South America. But right before he’s due to leave London, Poirot discovers that a man has broken into his apartment. The addled stranger, covered in dust and mud, can do little more than repeat Poirot’s address and draw the number 4 over and over. Could the Big Four, a shadowy and seemingly all-powerful organization, be behind these and other strange events?</p>\n\t\t\t<p>To stay ahead of supercriminals, Poirot needs the loyalty of his friend Captain Hastings almost as much as he needs his little grey cells. Soon they are rushing to country houses, a mysterious laboratory, the site of a deadly chess game, and a mountaintop hideaway in the Alps.</p>\n\t\t\t<p>The year before this book was published, personal turmoil made it impossible for <a href="https://standardebooks.org/ebooks/agatha-christie">Agatha Christie</a> to write—but her publisher was anxious for another novel to follow the highly successful <a href="https://standardebooks.org/ebooks/agatha-christie/the-murder-of-roger-ackroyd"><i>Murder of Roger Ackroyd</i></a>.</p>\n\t\t\t<p>Her brother-in-law helped her turn a twelve-part serial she had written several years before into <i>The Big Four</i>, and it’s this origin as separate stories that helps explain its occasional choppiness. As much a thriller as a mystery novel, the novel has never been considered her finest work by either readers or Christie herself, but it remains a fascinating example of Poirot and Hastings at their most spy-like and adventurous.</p>\n\t\t    en-GB         55818           76.62                     https://github.com/standardebooks/agatha-christie_the-big-four             https://en.wikipedia.org/wiki/The_Big_Four_(novel)               1927  Agatha Christie                        novel                 Detective|Espionage|Thriller         Hercule Poirot
the-man-in-the-brown-suit        Standard Ebooks        The Man in the Brown Suit  Agatha Christie                                                                                                                    South Africa -- Fiction|Detective and mystery stories|London (England) -- Fiction|Murder -- Investigation -- Fiction|Women adventurers  Adventure|Fiction|Mystery   series           Colonel Race          1  Anne Beddingfeld travels to South Africa after finding a cryptic note beside the body of a man whose death she witnessed in the London Underground.  \n\t\t\t<p>After her father’s death, young Anne Beddingfeld moves to London with her meagre inheritance, hopeful and ready to meet adventure. She witnesses a fatal accident at a Tube station and picks up a cryptic note dropped by the anonymous doctor who appeared on the scene. When Anne learns of a murder at the estate that the dead man was on his way to visit, it confirms her suspicion that the man in the brown suit who lost the note was not a real doctor.</p>\n\t\t\t<p>With her clue in hand she gains a commission from the newspaper leading the search for the “man in the brown suit,” and her investigation leads her to take passage on a South Africa–bound ocean liner. On board, she meets a famous socialite, a fake missionary, a possible secret service agent, and the <abbr>M.P.</abbr> at whose estate the second murder occurred. She learns about a secretive criminal mastermind known only as the Colonel and of stolen diamonds connected to it all.</p>\n\t\t\t<p>During the voyage, she evades an attempt on her life, and in South Africa she escapes from a kidnapping and barely survives another attack on her at Victoria Falls. She falls in love, finds the diamonds, and discovers the truth about the two deaths in London that started it all. Finally, she confronts the mysterious criminal mastermind, the Colonel.</p>\n\t\t\t<p>Published in 1924 by the Bodley Head, <i>The Man in the Brown Suit</i> is <a href="https://standardebooks.org/ebooks/agatha-christie">Agatha Christie’s</a> fourth novel. Unlike the classic murder mysteries that made her famous, <i>The Man in the Brown Suit</i>, like her second novel <i><a href="https://standardebooks.org/ebooks/agatha-christie/the-secret-adversary">The Secret Adversary</a></i>, is an international crime thriller.</p>\n\t\t    en-GB         75682           76.82        https://github.com/standardebooks/agatha-christie_the-man-in-the-brown-suit        https://en.wikipedia.org/wiki/The_Man_in_the_Brown_Suit               1924  Agatha Christie                        novel                      Murder Mystery|Thriller           Colonel Race
the-murder-at-the-vicarage       Standard Ebooks       The Murder at the Vicarage  Agatha Christie                                                                                                                                                                           Marple, Jane (Fictitious character)--Fiction|Women detectives--England--Fiction            Fiction|Mystery   series            Miss Marple          1          A vicar attempts to unravel the mystery of a murder that took place in his study, while his neighbor—an elderly spinster—takes an interest.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \n\t\t\t<p>Not much happens in the sleepy rural town of St. Mary Mead—but that all changes when Colonel Protheroe, a “pompous old brute,” is murdered while awaiting the Vicar in the vicarage study. The main problem isn’t the paucity of suspects—in this case, there seem to be too many willing to confess to the crime.</p>\n\t\t\t<p>The Vicar, who narrates the story, does his best to unravel the mystery himself, as the police seem not to be making a very good job of it. His investigation soon begins to benefit from the observations of his neighbor, a gossipy old spinster by the name of <a href="https://standardebooks.org/collections/miss-marple">Miss Marple</a>.</p>\n\t\t\t<p>This wasn’t Miss Marple’s first fictional appearance: she had played a part in an <a href="https://standardebooks.org/ebooks/agatha-christie">Agatha Christie</a> short story three years earlier. Miss Marple went on to become one of Christie’s most enduring and endearing characters, portrayed in many adaptations for television, stage, and film.</p>\n\t\t    en-GB         70129           77.84       https://github.com/standardebooks/agatha-christie_the-murder-at-the-vicarage       https://en.wikipedia.org/wiki/The_Murder_at_the_Vicarage               1930  Agatha Christie                        novel                               Murder Mystery       Miss Jane Marple
the-murder-of-roger-ackroyd      Standard Ebooks      The Murder of Roger Ackroyd  Agatha Christie                                                                                       Private investigators -- England -- Fiction|Detective and mystery stories, English|Belgians -- England -- Fiction|Poirot, Hercule (Fictitious character) -- Fiction                    Mystery   series                 Poirot          4                                                              A legendary Belgian detective comes out of retirement to investigate a friend’s murder.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \n\t\t\t<p>Hercule Poirot has retired to the English village of King’s Abbot, determined to use his little grey cells in the growing of vegetable marrows. But when Roger Ackroyd, a local businessman and former acquaintance of Poirot’s, is murdered, the man’s niece begs Poirot to investigate in order to clear her fiancé. With Hastings having married and moved to Argentina, Poirot enlists the local doctor to be his assistant and scribe, and the two of them sift through clues to try to discern the ones that will lead them to the killer.</p>\n\t\t\t<p><a href="https://standardebooks.org/ebooks/agatha-christie">Agatha Christie’s</a> two previous Poirot novels had been generally well-received, but <i>The Murder of Roger Ackroyd</i> made her a household name. Consistently ranked among Christie’s best works, in 2013 it was voted as the best crime novel ever written by the 600-member Crime Writers’ Association of the United Kingdom.</p>\n\t\t    en-GB         70105           77.84      https://github.com/standardebooks/agatha-christie_the-murder-of-roger-ackroyd      https://en.wikipedia.org/wiki/The_Murder_of_Roger_Ackroyd               1926  Agatha Christie                        novel                     Murder Mystery|Detective         Hercule Poirot

In [45]:
# fix data types
LIB['pub_year_original'] = LIB['pub_year_original'].astype('Int64')
LIB['se_word_count'] = LIB['se_word_count'].astype('Int64')
LIB['se_reading_ease'] = LIB['se_reading_ease'].astype('float64')

In [46]:
# save to csv

LIB.to_csv('data/LIB.csv', sep='\t', index=True)