01-lib.ipynb
02-corpus.ipynb
03-vocab.ipynb
04-dtm-tfidf.ipynb
05-pca.ipynb
06-lda.ipynb
07-sentiment.ipynb
08-word2vec.ipynb
09-riffs.ipynb

## Construct CORPUS table

First I am going to look at the files that make up each of the StandardEbooks.

For Giant's Bread which has book and chapter separations, I am going to do the following: as book in the giants bread is a product of publishing (i believe) rather than narrative, I will just continue the numbering making 2-1 be the next number after 1-x ends (REWRITE)

In [126]:
# import libraries
import pandas as pd
import glob
import os
import re
import nltk
import xml.etree.ElementTree as ET
from pathlib import Path
from bs4 import BeautifulSoup

In [127]:
nltk_resources = [
    'punkt_tab',
    'averaged_perceptron_tagger_eng',
    'stopwords',
    'tagsets'
]

for resource in nltk_resources:
    try:
        nltk.download(resource, quiet=True)
    except Exception as e:
        print(f"Could not download {resource}: {e}")

In [128]:
# get list of all files in the raw_data folder
root_dir = 'raw_data'
file_dict = {}

# get paths to xhtml files
paths = sorted(Path(root_dir).glob('*/src/epub/text/*.xhtml')) # glob finds all the pathnames matching a specified pattern

for path in paths:
    book_id = path.parts[1].replace('agatha-christie_', '') # .parts breaks a path into a tuple of components
    # for each book_id, get the file path to all xhtml files
    if book_id not in file_dict:
        file_dict[book_id] = []
    file_dict[book_id].append(path)

file_dict

{'giants-bread': [PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/book-1.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/book-2.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/book-3.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/book-4.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/book-5.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-1-1.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-1-2.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-1-3.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-1-4.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-1-5.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-1-6.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-1-7.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-1-8.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-2-1.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-2-2.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-2-3.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-2-4.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-2-5.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-2-6.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-2-7.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-3-1.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-3-2.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-3-3.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-3-4.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-4-1.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-4-2.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-4-3.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-4-4.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-5-1.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-5-2.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-5-3.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-5-4.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/chapter-5-5.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/colophon.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/imprint.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/prologue.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/titlepage.xhtml'),
  PosixPath('raw_data/agatha-christie_giants-bread/src/epub/text/uncopyright.xhtml')],
 'poirot-investigates': [PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/colophon.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/imprint.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/loi.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-adventure-of-the-cheap-flat.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-adventure-of-the-egyptian-tomb.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-adventure-of-the-italian-nobleman.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-adventure-of-the-western-star.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-case-of-the-missing-will.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-disappearance-of-mr-davenheim.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-jewel-robbery-at-the-grand-metropolitan.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-kidnapped-prime-minister.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-million-dollar-bond-robbery.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-mystery-of-hunters-lodge.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/the-tragedy-at-marsdon-manor.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/titlepage.xhtml'),
  PosixPath('raw_data/agatha-christie_poirot-investigates/src/epub/text/uncopyright.xhtml')],
 'the-big-four': [PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-1.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-10.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-11.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-12.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-13.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-14.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-15.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-16.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-17.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-18.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-2.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-3.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-4.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-5.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-6.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-7.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-8.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/chapter-9.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/colophon.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/imprint.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/titlepage.xhtml'),
  PosixPath('raw_data/agatha-christie_the-big-four/src/epub/text/uncopyright.xhtml')],
 'the-man-in-the-brown-suit': [PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-1.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-10.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-11.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-12.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-13.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-14.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-15.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-16.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-17.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-18.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-19.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-2.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-20.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-21.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-22.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-23.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-24.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-25.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-26.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-27.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-28.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-29.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-3.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-30.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-31.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-32.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-33.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-34.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-35.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-36.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-4.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-5.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-6.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-7.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-8.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/chapter-9.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/colophon.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/dedication.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/halftitlepage.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/imprint.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/loi.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/prologue.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/titlepage.xhtml'),
  PosixPath('raw_data/agatha-christie_the-man-in-the-brown-suit/src/epub/text/uncopyright.xhtml')],
 'the-murder-at-the-vicarage': [PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-1.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-10.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-11.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-12.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-13.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-14.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-15.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-16.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-17.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-18.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-19.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-2.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-20.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-21.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-22.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-23.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-24.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-25.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-26.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-27.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-28.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-29.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-3.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-30.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-31.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-32.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-4.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-5.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-6.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-7.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-8.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/chapter-9.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/colophon.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/dedication.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/halftitlepage.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/imprint.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/loi.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/titlepage.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-at-the-vicarage/src/epub/text/uncopyright.xhtml')],
 'the-murder-of-roger-ackroyd': [PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-1.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-10.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-11.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-12.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-13.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-14.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-15.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-16.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-17.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-18.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-19.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-2.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-20.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-21.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-22.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-23.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-24.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-25.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-26.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-27.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-3.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-4.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-5.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-6.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-7.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-8.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/chapter-9.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/colophon.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/dedication.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/halftitlepage.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/imprint.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/loi.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/titlepage.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-of-roger-ackroyd/src/epub/text/uncopyright.xhtml')],
 'the-murder-on-the-links': [PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-1.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-10.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-11.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-12.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-13.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-14.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-15.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-16.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-17.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-18.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-19.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-2.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-20.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-21.xhtml'),
  PosixPath('raw_data/agatha-christie_the-murder-on-the-links/src/epub/text/chapter-22.xhtml'),

### Write helper functions

In [129]:
BOILERPLATE = {'colophon', 'imprint', 'titlepage', 'uncopyright', 
               'halftitlepage', 'loi', 'dedication'}

def is_content(path):
    stem = path.stem
    if stem in BOILERPLATE:
        return False
    if stem.startswith('book-'):
        return False
    return True

In [130]:
GIANTS_BREAD_CHAPTER_COUNTS = {1: 8, 2: 7, 3: 4, 4: 4, 5: 5}

# make helper function
def get_chap_num(book_id, stem):
    if stem == 'prologue':
        chap_num = 0
    elif book_id == 'giants-bread' and stem.startswith('chapter-'):
        # get the numbers
        N = int(stem.split('-')[1])
        M = int(stem.split('-')[2])
        # cumulative offset for giants bread chapters
        chap_num = sum(count for book, count in GIANTS_BREAD_CHAPTER_COUNTS.items() if book < N) + M
    elif stem.startswith('chapter-'):
        # get the number
        N = int(stem.split('-')[1])
        chap_num = N
    else:
        raise ValueError(f"Cannot determine chap_num for book_id='{book_id}', stem='{stem}'")
    
    return chap_num

In [131]:
# test
print(get_chap_num('the-big-four', 'chapter-5'))        # expect 5
print(get_chap_num('giants-bread', 'chapter-2-3'))      # expect 11
print(get_chap_num('the-secret-adversary', 'prologue')) # expect 0

5
11
0

In [132]:
def tokenize_file(book_id, chap_num, xhtml_path):
    """
    Returns a TOKENS dataframe for one file.
    Uses some of the logic from the tokenize_source() function from HW 4.
    """
    # open file and parse with BeautifulSoup
    with open(xhtml_path, "r") as f:
        soup = BeautifulSoup(f, 'xml')
    # find all <p> tags to get list of paragraph text and filter out chap title
    text_paras = [p.get_text() for p in soup.find_all('p')
                  if 'title' not in p.get('epub:type', '')] # this is a list

    # create paragraph dataframe (must wrap the list in a series to use to_frame)
    PARAS = pd.Series(text_paras).to_frame('para_str')

    # parse into sentences with NLTK's sent_tokenize() method
    SENTS = PARAS.para_str.apply(lambda x: pd.Series(nltk.sent_tokenize(x), dtype = 'string'))\
        .stack().to_frame('sent_str')
    # cleanup (don't need PARAS df object anymore)
    del(PARAS)
    # drop NaN values from sents (empty paragraphs that became NaN after stack operation)
    SENTS = SENTS.dropna(subset=['sent_str'])

    # parse into tokens with NLTK's word_tokenize() method
    TOKENS = SENTS.sent_str.apply(lambda x: pd.Series(nltk.pos_tag(nltk.word_tokenize(x))))\
        .stack().to_frame('pos_tuple')
    # drop NaN values (empty tuples that became NaN after stack operation)
    TOKENS = TOKENS.dropna(subset=['pos_tuple'])
    TOKENS['pos'] = TOKENS.pos_tuple.apply(lambda x: x[1])
    TOKENS['pos_group'] = TOKENS.pos.str[:2]
    TOKENS['token_str'] = TOKENS.pos_tuple.apply(lambda x: x[0])
    # cleanup: don't need pos_tuple anymore
    TOKENS = TOKENS.drop('pos_tuple', axis = 1)
    TOKENS['term_str'] = TOKENS.token_str.str.lower().str.replace(r"[\W_]+", "", regex = True)
    TOKENS = TOKENS[TOKENS.term_str != ''].copy() # copy() ensures working on a dataframe rather than a view of one; good to include after bool filtering
    # cleanup (don't need SENTS df object anymore)
    del(SENTS)

    # add the chap_num and book_id (which are constant per file)
    TOKENS['chap_num'] = chap_num
    TOKENS['book_id'] = book_id

    # name, set, and order indices
    TOKENS.index.names = ['para_num', 'sent_num', 'token_num']
    TOKENS = TOKENS.set_index(['book_id', 'chap_num'], append=True)
    TOKENS = TOKENS.reorder_levels(['book_id', 'chap_num', 'para_num', 'sent_num', 'token_num'])

    return TOKENS

In [133]:
# test
tokenize_file('the-big-four', 1, 'raw_data/agatha-christie_the-big-four/src/epub/text/chapter-1.xhtml')

                                                   pos pos_group token_str  \
book_id      chap_num para_num sent_num token_num
the-big-four 1        0        0        0          PRP        PR         I
                                        1          VBP        VB      have
                                        2          VBN        VB       met
                                        3          NNS        NN    people
                                        4           WP        WP       who
...                                                ...       ...       ...
                      100      1        11         PRP        PR         I
                                        12          MD        MD       can
                                        13          VB        VB    manage
                                        14          DT        DT       the
                                        15          NN        NN      rest

                                                  term_str
book_id      chap_num para_num sent_num token_num
the-big-four 1        0        0        0                i
                                        1             have
                                        2              met
                                        3           people
                                        4              who
...                                                    ...
                      100      1        11               i
                                        12             can
                                        13          manage
                                        14             the
                                        15            rest

[2780 rows x 4 columns]

### Main parsing loop

In [ ]:
# tokenize source and append to list of corpora

# initialize list of corpora
corpus = []

# do i need a comment here???
for book_id, paths in file_dict.items():
    for path in paths:
        if is_content(path): # if not boilerplate
            print(book_id, path.stem) # see which file is being processed
            # if poirot-investigates, I to handle the short stories (stored the way all other books have chapters) as books themselves
            if book_id == 'poirot-investigates': # this is the book_id from the filepath, not the book_id I use in LIB
                story_id = path.stem
                chap_num = 1
                corpus.append(tokenize_file(story_id, chap_num, path))
            # if any other work
            else:
                chap_num = get_chap_num(book_id, path.stem)
                corpus.append(tokenize_file(book_id, chap_num, path))

CORPUS = pd.concat(corpus) # the dataframes already have the full OHCO index set (do not set here or we end up with another level)
print("\nDone!")
# cleanup
del(corpus)

giants-bread chapter-1-1
giants-bread chapter-1-2
giants-bread chapter-1-3
giants-bread chapter-1-4
giants-bread chapter-1-5
giants-bread chapter-1-6
giants-bread chapter-1-7
giants-bread chapter-1-8
giants-bread chapter-2-1
giants-bread chapter-2-2
giants-bread chapter-2-3
giants-bread chapter-2-4
giants-bread chapter-2-5
giants-bread chapter-2-6
giants-bread chapter-2-7
giants-bread chapter-3-1
giants-bread chapter-3-2
giants-bread chapter-3-3
giants-bread chapter-3-4
giants-bread chapter-4-1
giants-bread chapter-4-2
giants-bread chapter-4-3
giants-bread chapter-4-4
giants-bread chapter-5-1
giants-bread chapter-5-2
giants-bread chapter-5-3
giants-bread chapter-5-4
giants-bread chapter-5-5
giants-bread prologue
poirot-investigates the-adventure-of-the-cheap-flat
poirot-investigates the-adventure-of-the-egyptian-tomb
poirot-investigates the-adventure-of-the-italian-nobleman
poirot-investigates the-adventure-of-the-western-star
poirot-investigates the-case-of-the-missing-will
poirot-investigates the-disappearance-of-mr-davenheim
poirot-investigates the-jewel-robbery-at-the-grand-metropolitan
poirot-investigates the-kidnapped-prime-minister
poirot-investigates the-million-dollar-bond-robbery
poirot-investigates the-mystery-of-hunters-lodge
poirot-investigates the-tragedy-at-marsdon-manor
the-big-four chapter-1
the-big-four chapter-10
the-big-four chapter-11
the-big-four chapter-12
the-big-four chapter-13
the-big-four chapter-14
the-big-four chapter-15
the-big-four chapter-16
the-big-four chapter-17
the-big-four chapter-18
the-big-four chapter-2
the-big-four chapter-3
the-big-four chapter-4
the-big-four chapter-5
the-big-four chapter-6
the-big-four chapter-7
the-big-four chapter-8
the-big-four chapter-9
the-man-in-the-brown-suit chapter-1
the-man-in-the-brown-suit chapter-10
the-man-in-the-brown-suit chapter-11
the-man-in-the-brown-suit chapter-12
the-man-in-the-brown-suit chapter-13
the-man-in-the-brown-suit chapter-14
the-man-in-the-brown-suit chapter-15
the-man-in-the-brown-suit chapter-16
the-man-in-the-brown-suit chapter-17
the-man-in-the-brown-suit chapter-18
the-man-in-the-brown-suit chapter-19
the-man-in-the-brown-suit chapter-2
the-man-in-the-brown-suit chapter-20
the-man-in-the-brown-suit chapter-21
the-man-in-the-brown-suit chapter-22
the-man-in-the-brown-suit chapter-23
the-man-in-the-brown-suit chapter-24
the-man-in-the-brown-suit chapter-25
the-man-in-the-brown-suit chapter-26
the-man-in-the-brown-suit chapter-27
the-man-in-the-brown-suit chapter-28
the-man-in-the-brown-suit chapter-29
the-man-in-the-brown-suit chapter-3
the-man-in-the-brown-suit chapter-30
the-man-in-the-brown-suit chapter-31
the-man-in-the-brown-suit chapter-32
the-man-in-the-brown-suit chapter-33
the-man-in-the-brown-suit chapter-34
the-man-in-the-brown-suit chapter-35
the-man-in-the-brown-suit chapter-36
the-man-in-the-brown-suit chapter-4
the-man-in-the-brown-suit chapter-5
the-man-in-the-brown-suit chapter-6
the-man-in-the-brown-suit chapter-7
the-man-in-the-brown-suit chapter-8
the-man-in-the-brown-suit chapter-9
the-man-in-the-brown-suit prologue
the-murder-at-the-vicarage chapter-1
the-murder-at-the-vicarage chapter-10
the-murder-at-the-vicarage chapter-11
the-murder-at-the-vicarage chapter-12
the-murder-at-the-vicarage chapter-13
the-murder-at-the-vicarage chapter-14
the-murder-at-the-vicarage chapter-15
the-murder-at-the-vicarage chapter-16
the-murder-at-the-vicarage chapter-17
the-murder-at-the-vicarage chapter-18
the-murder-at-the-vicarage chapter-19
the-murder-at-the-vicarage chapter-2
the-murder-at-the-vicarage chapter-20
the-murder-at-the-vicarage chapter-21
the-murder-at-the-vicarage chapter-22
the-murder-at-the-vicarage chapter-23
the-murder-at-the-vicarage chapter-24
the-murder-at-the-vicarage chapter-25
the-murder-at-the-vicarage chapter-26
the-murder-at-the-vicarage chapter-27
the-murder-at-the-vicarage chapter-28
the-murder-at-the-vicarage chapter-29
the-murder-at-the-vicarage chapter-3
the-murder-at-the-vicarage chapter-30
the-murder-at-the-vicarage chapter-31
the-murder-at-the-vicarage chapter-32
the-murder-at-the-vicarage chapter-4
the-murder-at-the-vicarage chapter-5
the-murder-at-the-vicarage chapter-6
the-murder-at-the-vicarage chapter-7
the-murder-at-the-vicarage chapter-8
the-murder-at-the-vicarage chapter-9
the-murder-of-roger-ackroyd chapter-1
the-murder-of-roger-ackroyd chapter-10
the-murder-of-roger-ackroyd chapter-11
the-murder-of-roger-ackroyd chapter-12
the-murder-of-roger-ackroyd chapter-13
the-murder-of-roger-ackroyd chapter-14
the-murder-of-roger-ackroyd chapter-15
the-murder-of-roger-ackroyd chapter-16
the-murder-of-roger-ackroyd chapter-17
the-murder-of-roger-ackroyd chapter-18
the-murder-of-roger-ackroyd chapter-19
the-murder-of-roger-ackroyd chapter-2
the-murder-of-roger-ackroyd chapter-20
the-murder-of-roger-ackroyd chapter-21
the-murder-of-roger-ackroyd chapter-22
the-murder-of-roger-ackroyd chapter-23
the-murder-of-roger-ackroyd chapter-24
the-murder-of-roger-ackroyd chapter-25
the-murder-of-roger-ackroyd chapter-26
the-murder-of-roger-ackroyd chapter-27
the-murder-of-roger-ackroyd chapter-3
the-murder-of-roger-ackroyd chapter-4
the-murder-of-roger-ackroyd chapter-5
the-murder-of-roger-ackroyd chapter-6
the-murder-of-roger-ackroyd chapter-7
the-murder-of-roger-ackroyd chapter-8
the-murder-of-roger-ackroyd chapter-9
the-murder-on-the-links chapter-1
the-murder-on-the-links chapter-10
the-murder-on-the-links chapter-11
the-murder-on-the-links chapter-12
the-murder-on-the-links chapter-13
the-murder-on-the-links chapter-14
the-murder-on-the-links chapter-15
the-murder-on-the-links chapter-16
the-murder-on-the-links chapter-17
the-murder-on-the-links chapter-18
the-murder-on-the-links chapter-19
the-murder-on-the-links chapter-2
the-murder-on-the-links chapter-20
the-murder-on-the-links chapter-21
the-murder-on-the-links chapter-22
the-murder-on-the-links chapter-23
the-murder-on-the-links chapter-24
the-murder-on-the-links chapter-25
the-murder-on-the-links chapter-26
the-murder-on-the-links chapter-27
the-murder-on-the-links chapter-28
the-murder-on-the-links chapter-3
the-murder-on-the-links chapter-4
the-murder-on-the-links chapter-5
the-murder-on-the-links chapter-6
the-murder-on-the-links chapter-7
the-murder-on-the-links chapter-8
the-murder-on-the-links chapter-9
the-mysterious-affair-at-styles chapter-1
the-mysterious-affair-at-styles chapter-10
the-mysterious-affair-at-styles chapter-11
the-mysterious-affair-at-styles chapter-12
the-mysterious-affair-at-styles chapter-13
the-mysterious-affair-at-styles chapter-2
the-mysterious-affair-at-styles chapter-3
the-mysterious-affair-at-styles chapter-4
the-mysterious-affair-at-styles chapter-5
the-mysterious-affair-at-styles chapter-6
the-mysterious-affair-at-styles chapter-7
the-mysterious-affair-at-styles chapter-8
the-mysterious-affair-at-styles chapter-9
the-mystery-of-the-blue-train chapter-1
the-mystery-of-the-blue-train chapter-10
the-mystery-of-the-blue-train chapter-11
the-mystery-of-the-blue-train chapter-12
the-mystery-of-the-blue-train chapter-13
the-mystery-of-the-blue-train chapter-14
the-mystery-of-the-blue-train chapter-15
the-mystery-of-the-blue-train chapter-16
the-mystery-of-the-blue-train chapter-17
the-mystery-of-the-blue-train chapter-18
the-mystery-of-the-blue-train chapter-19
the-mystery-of-the-blue-train chapter-2
the-mystery-of-the-blue-train chapter-20
the-mystery-of-the-blue-train chapter-21
the-mystery-of-the-blue-train chapter-22
the-mystery-of-the-blue-train chapter-23
the-mystery-of-the-blue-train chapter-24
the-mystery-of-the-blue-train chapter-25
the-mystery-of-the-blue-train chapter-26
the-mystery-of-the-blue-train chapter-27
the-mystery-of-the-blue-train chapter-28
the-mystery-of-the-blue-train chapter-29
the-mystery-of-the-blue-train chapter-3
the-mystery-of-the-blue-train chapter-30
the-mystery-of-the-blue-train chapter-31
the-mystery-of-the-blue-train chapter-32
the-mystery-of-the-blue-train chapter-33
the-mystery-of-the-blue-train chapter-34
the-mystery-of-the-blue-train chapter-35
the-mystery-of-the-blue-train chapter-36
the-mystery-of-the-blue-train chapter-4
the-mystery-of-the-blue-train chapter-5
the-mystery-of-the-blue-train chapter-6
the-mystery-of-the-blue-train chapter-7
the-mystery-of-the-blue-train chapter-8
the-mystery-of-the-blue-train chapter-9
the-secret-adversary chapter-1
the-secret-adversary chapter-10
the-secret-adversary chapter-11
the-secret-adversary chapter-12
the-secret-adversary chapter-13
the-secret-adversary chapter-14
the-secret-adversary chapter-15
the-secret-adversary chapter-16
the-secret-adversary chapter-17
the-secret-adversary chapter-18
the-secret-adversary chapter-19
the-secret-adversary chapter-2
the-secret-adversary chapter-20
the-secret-adversary chapter-21
the-secret-adversary chapter-22
the-secret-adversary chapter-23
the-secret-adversary chapter-24
the-secret-adversary chapter-25
the-secret-adversary chapter-26
the-secret-adversary chapter-27
the-secret-adversary chapter-28
the-secret-adversary chapter-3
the-secret-adversary chapter-4
the-secret-adversary chapter-5
the-secret-adversary chapter-6
the-secret-adversary chapter-7
the-secret-adversary chapter-8
the-secret-adversary chapter-9
the-secret-adversary prologue
the-secret-of-chimneys chapter-1
the-secret-of-chimneys chapter-10
the-secret-of-chimneys chapter-11
the-secret-of-chimneys chapter-12
the-secret-of-chimneys chapter-13
the-secret-of-chimneys chapter-14
the-secret-of-chimneys chapter-15
the-secret-of-chimneys chapter-16
the-secret-of-chimneys chapter-17
the-secret-of-chimneys chapter-18
the-secret-of-chimneys chapter-19
the-secret-of-chimneys chapter-2
the-secret-of-chimneys chapter-20
the-secret-of-chimneys chapter-21
the-secret-of-chimneys chapter-22
the-secret-of-chimneys chapter-23
the-secret-of-chimneys chapter-24
the-secret-of-chimneys chapter-25
the-secret-of-chimneys chapter-26
the-secret-of-chimneys chapter-27
the-secret-of-chimneys chapter-28
the-secret-of-chimneys chapter-29
the-secret-of-chimneys chapter-3
the-secret-of-chimneys chapter-30
the-secret-of-chimneys chapter-31
the-secret-of-chimneys chapter-4
the-secret-of-chimneys chapter-5
the-secret-of-chimneys chapter-6
the-secret-of-chimneys chapter-7
the-secret-of-chimneys chapter-8
the-secret-of-chimneys chapter-9
the-seven-dials-mystery chapter-1
the-seven-dials-mystery chapter-10
the-seven-dials-mystery chapter-11
the-seven-dials-mystery chapter-12
the-seven-dials-mystery chapter-13
the-seven-dials-mystery chapter-14
the-seven-dials-mystery chapter-15
the-seven-dials-mystery chapter-16
the-seven-dials-mystery chapter-17
the-seven-dials-mystery chapter-18
the-seven-dials-mystery chapter-19
the-seven-dials-mystery chapter-2
the-seven-dials-mystery chapter-20
the-seven-dials-mystery chapter-21
the-seven-dials-mystery chapter-22
the-seven-dials-mystery chapter-23
the-seven-dials-mystery chapter-24
the-seven-dials-mystery chapter-25
the-seven-dials-mystery chapter-26
the-seven-dials-mystery chapter-27
the-seven-dials-mystery chapter-28
the-seven-dials-mystery chapter-29
the-seven-dials-mystery chapter-3
the-seven-dials-mystery chapter-30
the-seven-dials-mystery chapter-31
the-seven-dials-mystery chapter-32
the-seven-dials-mystery chapter-33
the-seven-dials-mystery chapter-34
the-seven-dials-mystery chapter-4
the-seven-dials-mystery chapter-5
the-seven-dials-mystery chapter-6
the-seven-dials-mystery chapter-7
the-seven-dials-mystery chapter-8
the-seven-dials-mystery chapter-9
Done

In [138]:
CORPUS

                                                              pos pos_group  \
book_id                 chap_num para_num sent_num token_num
giants-bread            1        0        0        0           EX        EX
                                                   1          VBD        VB
                                                   2           RB        RB
                                                   3           CD        CD
                                                   4          NNS        NN
...                                                           ...       ...
the-seven-dials-mystery 9        117      6        4           IN        IN
                                                   5          NNP        NN
                                                   6          NNP        NN
                                                   7           RB        RB
                                                   8           JJ        JJ

                                                               token_str  \
book_id                 chap_num para_num sent_num token_num
giants-bread            1        0        0        0               There
                                                   1                were
                                                   2                only
                                                   3               three
                                                   4              people
...                                                                  ...
the-seven-dials-mystery 9        117      6        4                  of
                                                   5             Loraine
                                                   6                Wade
                                                   7              highly
                                                   8          suspicious

                                                                term_str
book_id                 chap_num para_num sent_num token_num
giants-bread            1        0        0        0               there
                                                   1                were
                                                   2                only
                                                   3               three
                                                   4              people
...                                                                  ...
the-seven-dials-mystery 9        117      6        4                  of
                                                   5             loraine
                                                   6                wade
                                                   7              highly
                                                   8          suspicious

[852006 rows x 4 columns]