# Data Gathering

*I am in the process of adapting this old assignment into my outline for webscraping my data for my final proj*

I will be grabbing the discographies of
- joni mitchell
- indigo girls
- natalie merchant?
- melissa etheridge?

# TO DO???
- add artist, nubmer of songs, release date to LIB?
- make corpus table
- maybe separate tokenization from corpus build function?
- add track numbers to protect track order within albums

OHCO = ['album_title', 'track_num', 'song_title', 'stanza_num', 'line_num', 'token_num']

SHOULD SONG TITLE BE IN HERE?

## Import packages

In [2]:
import numpy as np
import pandas as pd
import requests
import time
import json
import lyricsgenius
import dotenv
import os
from bs4 import BeautifulSoup

# Get Data - Indigo Girls

In [ ]:
# # bring in API key from .env file
# dotenv.load_dotenv()
# geniuskey = os.getenv("geniuskey")

# # set up user agent headers and pass API key via HTTP
# # auth header for Genius API preceded by the word "Bearer" and a space
# useragent = f'BeanBot/2.2 (bhj3vc@virginia.edu) python-requests/{requests.__version__}'
# headers = {
#     'User-Agent': useragent,
#     'Authorization': f'Bearer {geniuskey}'
# }

# # pull every song from every album
# genius = lyricsgenius.Genius(geniuskey)

# artist = genius.search_albu

{'User-Agent': 'BeanBot/2.2 (bhj3vc@virginia.edu) python-requests/2.32.5',
 'Authorization': 'Bearer S2INJcDYAlfMvj-qHr3t-3gY91t-eTiqooMIgkqVEnnDB0a2bUxrFuT7rJYdViV5K7_5WgVDIo_L2TLBrtfjSA'}

## Getting Indigo Girls Data from Lifeblood.net instead of lyricsgenius

In [ ]:
BASE_URL = "https://www.lifeblood.net"
ALBUMS

# Get Data - Joni Mitchell

## Write functions

In [ ]:
def get_album_urls(discography_url, headers, base_url='https://jonimitchell.com'):
    """
    Scrapes discography index and returns a list of dictionaries,
    each containing the album's URL, title, and release date.
    """

    # get discography page
    print(f"Pinging {discography_url} for album index...")
    r = requests.get(discography_url, headers=headers)

    # check if request was successful
    if r.status_code != 200:
        print(f"Warning: Received status code {r.status_code}.")
        return []

    # parse the html with BeautifulSoup
    soup = BeautifulSoup(r.text, 'html.parser')

    # target the div that contains all the info for a single album
    gallery_items = soup.find_all('div', class_='gallery-item')

    albums = []

    for item in gallery_items:
        # extract the URL
        a_tag = item.find('a', href=True)
        if not a_tag or 'album.cfm' not in a_tag['href']:
            continue # skip item if it doesn't have a valid album link
        
        full_url = base_url + a_tag['href']

        # extract title
        title_tag = item.find('span', class_='albumtitle')
        title = title_tag.text.strip() if title_tag else 'Unknown Title'
        
        # extract release date
        date_tag = item.find('span', class_='released')
        if date_tag:
            # remove the word "Released' so you just have Month Day Year
            release_date = date_tag.text.replace('Released ', '').strip()
        else:
            release_date = 'Unknown Date'

        # bind the info together into a single record
        album_record = {
            'album_url': full_url,
            'album_title': title,
            'release_date': release_date
        }

        albums.append(album_record)

    return albums

In [ ]:
def get_album_tracks(album_record, headers, base_url='https://jonimitchell.com'):
    """
    Takes a single album dictionary, visits its page, and returns a list of
    dictionaries representing the individual songs on that album.
    """

    album_url = album_record['album_url']
    print(f"  -> Digging into album: {album_record['album_title']}...")

    r = requests.get(album_url, headers=headers)
    time.sleep(2) # be polite to server and wait a few seconds before the next request
    
    if r.status_code != 200:
        print(f"  Warning: Received status code {r.status_code} for album page.")
        return []

    soup = BeautifulSoup(r.text, 'html.parser')

    # find the div that contains the track listing
    tracklist_ul = soup.find('ul', class_='tracklist') # ul in html means unordered list

    if not tracklist_ul:
        print("  Warning: No tracklist found on this page.")
        return []

    # extract links within the tracklist
    song_links = tracklist_ul.find_all('a', href=True)

    songs = []

    for link in song_links:
        href = link['href']

        # make sure its a song link
        if 'song.cfm?id=' not in href:
            continue # skip if it's not a valid song link

        # extract songs within tracklist
        song_title = link.contents[0].strip()

        # make sure the song title is not empty
        if not song_title:
            continue # skip if song title is empty

        # get url and title for each song and carry down album metadata
        song_record = {
            'song_url': base_url + href,
            'song_title': song_title,
            'album_title': album_record['album_title'], # preserving ohco hierarchy
            'release_date': album_record['release_date'] # preserving ohco hierarchy
        }

        songs.append(song_record)

    # remove duplicates
    # sometimes tracklists link the same song twice (clicking number v title for ex)
    unique_songs = {song['song_url']: song for song in songs}.values()

    return list(unique_songs)

In [ ]:
def get_song_lyrics(song_record, headers):
    """
    Visits a specific song page, extracts the author, lyrics, and copyright,
    and returns a complete, finalized dictionary for the corpus.
    """

    song_url = song_record['song_url']
    print(f"    -> Fetching lyrics for song: {song_record['song_title']}")

    r = requests.get(song_url, headers=headers)
    time.sleep(2) # be polite to server and wait a few seconds

    if r.status_code != 200:
        print(f"    Warning: Received status code {r.status_code} for song page.")
        song_record.update({'author': None, 'copyright': None, 'lyrics': None})
        return song_record

    soup = BeautifulSoup(r.text, 'html.parser')

    # extract the author
    # note the author tag is outside of the lyrics div, so we have to look for it separately by searching the whole soup
    author_tag = soup.find('p', class_='author')
    if author_tag:
        author_text = author_tag.text.strip()
        # clean the data: remove "by" if it exists at start of string and strip whitespace
        if author_text.lower().startswith('by '):
            author_text = author_text[3:].strip()
        song_record['author'] = author_text
    else:
        song_record['author'] = "Unknown"

    # target the lyrics container
    lyrics_div = soup.find('div', class_='songlyrics')

    if not lyrics_div:
        print("    Warning: No lyrics found on this page.")
        song_record.update({'copyright': None, 'lyrics': None})
        return song_record

    # extract copyright metadata
    copyright_tag = lyrics_div.find('p', class_='lyricscopyright')
    if copyright_tag:
        song_record['copyright'] = copyright_tag.text.replace('© ', '').strip()
    else:
        song_record['copyright'] = "Unknown"

    # extract OHCO-ready lyrics text
    lyrics_paragraphs = lyrics_div.find_all('p', class_=lambda x: x != 'lyricscopyright') # get all paragraphs except the copyright one
    
    raw_lyrics = []
    for p in lyrics_paragraphs:
        # get_text(separator='\n') will replace all <br> tags with actual line breaks
        raw_lyrics.append(p.get_text(separator='\n').strip())
    
    song_record['lyrics'] = '\n\n'.join(raw_lyrics)

    return song_record

In [ ]:
def build_joni_corpus(discography_url, headers, base_url='https://jonimitchell.com'):
    """
    Orchestrates the 3-level extraction pipeline and transforms the
    resulting data into an OHCO-formatted pandas DataFrame.
    """
    print("Starting corpus build process...\n")
    final_corpus = []

    # level 1: get album urls
    albums = get_album_urls(discography_url, headers, base_url)

    # optional albums = albums[:2] # for testing, limit to first 2 albums
    for album in albums:
        # level 2: get song urls by iterating through albums
        songs = get_album_tracks(album, headers, base_url + '/music/')

        for song in songs:
            # level 3: get lyrics and metadata for each song
            complete_record = get_song_lyrics(song, headers)
            final_corpus.append(complete_record)

    print("\nExtraction complete! Restructuring into OHCO format...")

    # OHCO transformation
    df = pd.DataFrame(final_corpus)
    
    # get rid of tracks with no lyrics (instrumentals, etc)
    df = df.dropna(subset=['lyrics'])

    # split into stanzas by double line break
    df_stanzas = df.set_index(['album_title', 'release_date', 'song_title', 'author', 'copyright', 'song_url'])['lyrics']\
        .str.split('\n\n', expand=True)\
        .stack()\
        .to_frame('stanza_text')
    
    df_stanzas.index.names = ['album_title', 'release_date', 'song_title', 'author', 'copyright', 'song_url', 'stanza_num']

    # split into lines
    df_lines = df_stanzas['stanza_text'].str.split('\n', expand=True)\
        .stack()\
        .to_frame('line_text')
    
    df_lines.index.names = ['album_title', 'release_date', 'song_title', 'author', 'copyright', 'song_url', 'stanza_num', 'line_num']
    df_lines['line_text'] = df_lines['line_text'].str.strip() # clean up whitespace

    # split lines into individual words
    # using whitespace and punctuation as delimiters for now
    # TO BE UPDATED USING NLTK OR OTHER METHODS FROM NOTES
    # using a regular expression (\W+ splits on any non-word character)
    df_tokens = df_lines['line_text'].str.split(r'\W+', expand=True)\
        .stack()\
        .to_frame('token_str')
    
    # name the deepest index level 'token_num'
    # dynamically grab existing index names from df_lines and add our new one
    df_tokens.index.names = list(df_lines.index.names) + ['token_num']

    # clean artifacts
    # lowercase all tokens
    df_tokens['token_str'] = df_tokens['token_str'].str.lower()

    # drop any empty strings that may have been created during regex split
    df_tokens = df_tokens[df_tokens['token_str'].notna() & (df_tokens['token_str'] != '')]

    print("Token-level OHCO built successfully.")
    return df_lines, df_tokens

## Build Corpus

In [ ]:
# setup
base_url = 'https://jonimitchell.com'
discography_url = f'{base_url}/music/index.cfm'
useragent = f'BeanBot/2.2 (bhj3vc@virginia.edu) python-requests/{requests.__version__}'
headers = {'User-Agent': useragent,
        'From': 'bhj3vc@virginia.edu'}

OHCO_corpus = build_joni_corpus(discography_url, headers, base_url)

Starting corpus build process...

Pinging https://jonimitchell.com/music/index.cfm for album index...
  -> Digging into album: Song to a Seagull...
    -> Fetching lyrics for song: I Had A King
    -> Fetching lyrics for song: Michael From Mountains
    -> Fetching lyrics for song: Night In The City
    -> Fetching lyrics for song: Marcie
    -> Fetching lyrics for song: Nathan La Franeer
    -> Fetching lyrics for song: Sisotowbell Lane
    -> Fetching lyrics for song: The Dawntreader
    -> Fetching lyrics for song: The Pirate Of Penance
    -> Fetching lyrics for song: Song To A Seagull
    -> Fetching lyrics for song: Cactus Tree

Extraction complete! Restructuring into OHCO format...
Token-level OHCO built successfully.

In [ ]:
# Assuming OHCO_corpus is the dataframe returned by your function

# 1. Create the LIB table (Unique metadata per album)
LIB = OHCO_corpus.index.to_frame().reset_index(drop=True)
LIB = LIB[['album_title', 'release_date']].drop_duplicates().set_index('album_title')
# LIB.to_csv('joni_mitchell_LIB.csv')

# 2. Create the CORPUS table (The lines)
# You can generate this by calling your function but stopping before the tokenization step
# CORPUS = df_lines # From our previous code block
# CORPUS.to_csv('joni_mitchell_CORPUS.csv')

# 3. Create the TOKEN table
TOKENS = OHCO_corpus # This is the final output of your pipeline
# TOKENS.to_csv('joni_mitchell_TOKENS.csv')

In [ ]:
LIB

                  release_date
album_title
Song to a Seagull   March 1968

In [ ]:
# CORPUS

In [ ]:
TOKENS

                                                                                                                                                                               token_str
album_title       release_date song_title   author        copyright                               song_url                                       stanza_num line_num token_num
Song to a Seagull March 1968   I Had A King Joni Mitchell February 9, 1968; Siquomb Publishing Co https://jonimitchell.com/music/song.cfm?id=130 0          0        0                 i
                                                                                                                                                                     1               had
                                                                                                                                                                     2                 a
                                                                                                                                                                     3              king
                                                                                                                                                                     4                in
...                                                                                                                                                                                  ...
                               Cactus Tree  Joni Mitchell April 1, 1968; Siquomb Publishing Corp  https://jonimitchell.com/music/song.cfm?id=84  4          24       2                 s
                                                                                                                                                                     3                so
                                                                                                                                                                     4              busy
                                                                                                                                                                     5             being
                                                                                                                                                                     6              free

[2578 rows x 1 columns]

# Attributions

I used Gemini to help debug errors with some of my functions. (Missing quotations, missing attributes, etc.)

I had Claude do the same to see if it responded differently.